### PR TITLE
Fix null collection copy crash on holder cache lookup

### PR DESCRIPTION
**Pull request by NerjalNosk**
Simple fix of an issue that arises any time holder cached lookup is called over NBT-strict entities

### CODE REVIEW

**Comment by NerjalNosk** [comment]
Side note, this crash also occurs upon player death when killed by such mobs, but while the death is saved, the player death workflow is still interrupted, thus causing a complete loss of the dead player's inventory

**Comment by Dragon-Seeker** [comment]
Can you send any example crash for this issue as I am looking at this code and find no reason for the return value to be nulll

**Comment by NerjalNosk** [comment]
Had [this](https://github.com/user-attachments/files/17512630/crash-2024-10-23_13.03.48-server.txt) occur while playing a tweaked version of [The Solar Apocalypse](https://modrinth.com/mod/9XJY0akS), upon dying to a zombie spawned by the [Underground Bunkers](https://modrinth.com/mod/underground-bunkers/version/1.0.4) structure's spawners.

**Comment by Dragon-Seeker** [comment]
@NerjalNosk Can you get this to occur consistently?

**Comment by NerjalNosk** [comment]
It does occur any time one of these mobs kills me, although I do admit I yet have to try out with other mobs than the Underground Bunker zombies (especially since I'd like to get through this world without having to cheat)

**Comment by Dragon-Seeker** [comment]
I have pushed an update attempting to fix the issue better, hopefully removing the bug though I still do not quite understand how it occurs. Thank you for the PR and notifying me of the issue

**Comment by NerjalNosk** [comment]
Well, you definitely know your mod better than I do, I have no doubts you have a better understanding of why this is occurring. Thanks for providing a fix for it!

**Pull request closed without merging**
