### PR TITLE
Create `ru_ru.json`

### PR DESCRIPTION
**Pull request by mpustovoi**

### CODE REVIEW

**Comment by Dragon-Seeker** [comment]
I have some changes to the existing lang file that may cause this PR to be out of date, but I would like to see about pulling such in / getting Russian Translations within Accessories.

**Comment by mpustovoi** [comment]
I can add the missing lines.

**Comment by Dragon-Seeker** [comment]
Ok so I will pull such PR in for 1.20.1 but if you are willing to wait for the upcoming `1.21.x-ScreenExperiments` and PR new translations that would be great as a bunch of translations will be added and adjusted requiring more work for complete translations on such version.

**Comment by mpustovoi** [comment]
I probably won't be able to do this in the near future, especially since there are 300+ lines to translate.

**Comment by Dragon-Seeker** [comment]
Understandable and no pressure with such if it can't be done in a timely manor, maybe possible to pull the given translations upstream for the time being and get such updated later for changes

**Pull request merged**
